### ISSUE TITLE
How Install and configure please?

### ISSUE THREAD

**Issue by jancelin** [balost/NTRIPLIB#1]
Hi,
I use bkg caster now but I search a open NtripCaster for my project [centipede](https://github.com/jancelin/centipede/blob/master/README.md).

how can I install and configure your caster to test?

best regards.
Julien

**Comment by hagre** [comment]
Hello,
I am facing the same problem as @jancelin. Please provide more information. 
thanks
hagre

**Comment by ybzwyrcld** [comment]
Hi,
    Sorry, I've been focusing on other projects recently, so I haven't updated the use of this project in 
  time. Now I have improved some features, and I hope they will help you.

best regards,
hanoi404
