### ISSUE TITLE
potentially wrong respone after mountpoit registration

### ISSUE THREAD

**Issue by ace-at-git** [balost/NTRIPLIB#3]
I tried to use the ntrip_caster together with this [ntripserver](https://github.com/goblimey/c-ntripserver).

I started the server similar to the following call to forward RTCM data from local serial interface to the caster:
`./ntripserver -M 1 -i /dev/ttyACM0 -O 1 -a <server-ip> -p <port> -m RTCM32 -n <user> -c <password> -N 'STR;RTCM32;RTCM32;RTCM 3.2;1004(1),1005/1007(5),PBS(10);2;GPS;SGNET;CHN;31;121;1;1;SGCAN;None;B;N;0;;'`

The ntripserver complains about:
ERROR: Destination caster's reply is not OK: ICY 200 OK
       Ntrip Version 2.0 not implemented at Destination caster <server-ip>

After changing ntrip_caster.cc line 481 from
      `SendData(sock, "ICY 200 OK\r\n", 12)`;
to
`      SendData(sock, "HTTP/1.1 200 OK\r\n", 17);`
it worked.

I can not judge if my proposed change is according to Ntrip Version 2.0 correct, but the ntrip_caster works with it for my use case. Even using the casted Ntrip data with [gpsd](https://gpsd.gitlab.io/gpsd/) on a different machine with a call similar to the following works:
`gpsd -N -G -D3 -n ntrip://<user>:<password>@<server-ip>:<port>/RTCM32 /dev/ttyACM1`

Anyhow, thank you for providing the nice code!

**Comment by ybzwyrcld** [comment]
For Ntrip Version 2.0, it should return `HTTP/1.1 200 OK\r\n`. 
Only the Ntrip Version 1.0 case is dealt with here.
Thank you for your reminder.
